name: calunedar
description: does calendar stuff + moon phases, good for gregorian, coligny, and
  attic (probably) right now
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  dart_date: ^1.0.9
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  geolocator: ^9.0.2
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  redux_thunk: ^0.4.0
  reselect: ^0.5.0
  solar_calculator: ^1.0.2
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  visibility_detector: ^0.4.0+2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  macos: false
  web: true
  windows: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/license_texts/
