name: calunedar
description: does calendar stuff + moon phases, good for gregorian and coligny right now
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_date: ^1.0.9
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_redux: ^0.8.2
  geolocator: ^8.0.5
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  redux_thunk: ^0.4.0
  reselect: ^0.5.0
  solar_calculator: ^1.0.2
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/license_texts/
