Map<String, List<List<List<String>>>> inscriptions = {
  "Quimonios": [
    [
      ["MD SIMIUIS GIAMONI", "IVOS"],
      ["MD SIMIUISONNA", "IVOS"],
      ["MD SIMIUIS EQUI", "IVOS"],
      ["D ELEMBI"],
      ["D EDRINNI AMB"],
      ["D CANTLOS"],
      ["MD PRINI LOUD SAMONI", "TINA D[---", "NE[---", "?I[---"],
      ["D SAMON DUMANI", "M[---"],
      ["MD DUMAN RIVRI", "EDVTIO[---", "MV[---"],
      ["D ANAGANT"],
      ["(IIT) D AMB OGRON"],
      ["(IIT) MD CUTIOS"],
      ["(TII) D GIAMON"],
      ["NSDS/D EQVI SIMIUIS"],
      ["MD SIMIUIS EQVI"],
      ["MD EDRINI ELEMB"],
      ["D ELEMB EDRINI"],
      ["(IIT) D CANTLI AMB RIXRI"],
      ["(TII) MD SAMON"],
      ["D DUMANNI AMB ?RI"],
      ["IIT MD RIVRI"],
      ["NSDS SAMONI ANAGAN", "INNIS R [----]TIT"],
      ["NSDS SAM OGRON QVTIO", "INNIS R"],
      ["N(SDS) SAM QVTIO INNIS R", "ED[----", "SV[----"],
      ["(TII) D GIAMON"],
      ["D AMB SIMIUS", "IVOS"],
      ["(ITI) D EQVI", "IVOS"],
      ["(ITI) D AMB ELEMB", "IVOS"],
      ["MD EDRINNI", "IVOS"],
    ],
    [],
    [],
    [],
    [],
  ],
  "Samonios": [
    [
      ["D DUMANNI", "IVOS"],
      ["MD", "IVOS"],
      ["TII D EXINGI DUM", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB * RIX * RI"],
      ["MD"],
      ["N DUMAN INIS R"],
      ["MD SAMONI"],
      ["D DUMANI"],
      ["MD"],
      ["D AMB"],
      ["MD [D M]"],
      ["MD [D M]"],
      ["MD [D M]"],
      ["MD [D M]"],
      ["D DUMANNI"],
      ["MD TRINO SAM SINDIV", "(IVOS)"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["D DUMANI AMB"],
      ["TII D DUMANI"],
      ["N DUM INIS R"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
    ],
    [
      ["N DUMANNI", "IVOS"],
      ["ITI MD", "IVOS"],
      ["TII D DUM ALE", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["PRINI LOUDIN"],
      ["D DUMANI"],
      ["IIT MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT MD"],
      ["D DUMANNI"],
      ["IIT MD TRINUX SAM"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["TII MD"],
      ["ITI D AMB", "IVOS"],
      ["IIT MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["N DUMANNI", "IVOS"],
      ["ITI MD", "IVOS"],
      ["TII D DUM ALE", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["PRINI LOUDIN"],
      ["D DUMANI"],
      ["IIT MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["N"],
      ["ITI MD"],
      ["IIT MD"],
      ["D DUMANNI"],
      ["IIT MD TRINUX SAM"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["TII MD"],
      ["ITI D AMB", "IVOS"],
      ["IIT MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["D DUMANNI", "IVOS"],
      ["MD", "IVOS"],
      ["D EXINGI DUM", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB"],
      ["MD"],
      ["N DUMAN INIS R"],
      ["MD SAMONI"],
      ["D DUMANI"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT MD"],
      ["D DUMANI"],
      ["(M)D PRINI (TRINUX) SAM SINDIV", "(IVOS)"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D DUM AMB"],
      ["D DUMANI"],
      ["N DUM INIS R"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
    ],
    [
      ["D DUMANNI", "IVOS"],
      ["MD", "IVOS"],
      ["TII D DUM ALE", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["N PRINI LOUDIN"],
      ["D DUMANI"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D DUMANNI"],
      ["MD TRINO SAM"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["TII MD"],
      ["ITI D AMB", "IVOS"],
      ["IIT MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
  ],
  "Dumanios": [
    [
      ["SAMON PRINI LOUD"],
      ["D"],
      ["D"],
      ["D"],
      ["PRINI LAG AMB"],
      ["ITI D"],
      ["MD RIVRI"],
      ["MD RIVRI"],
      ["MD RIVRI"],
      ["D"],
      ["N INIS R"],
      ["ITI D"],
      ["IIT D", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["MD SAMONI", "IVOS"],
      ["MD SAMONI", "IVOS"],
      ["ITI D AMB", "IVOS"],
      ["IIT D", "IVOS"],
      ["D AMB", "IVOS"],
      ["IIT D"],
      ["D RIVRI AMB"],
      ["D PETIUX RIV ANAG"],
      ["D AMB RIVRI"],
      ["IIT D"],
      ["D AMB", "[IVOS]"],
      ["N INIS R", "[IVOS]"],
      ["D AMB", "IVOS"],
      ["NSDS", "IVOS"],
    ],
    [
      ["SAM PRINI LOUD EXO", "IVOS"],
      ["N", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAGET"],
      ["D"],
      ["N INIS R"],
      ["ITI MD SAMONI"],
      ["D"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["MD SAMONI"],
      ["MD SAMONI"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["IIT M D"],
      ["D AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["NSDS"],
    ],
    [
      ["SAM PRINI LOUD EXO", "IVOS"],
      ["N", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAGET"],
      ["D"],
      ["N INIS R"],
      ["ITI MD SAMONI"],
      ["D"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D"],
      ["N"],
      ["D"],
      ["MD SAMONI"],
      ["MD SAMONI"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D AMB (N AMB)"],
      ["N INIS R"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["SAMON PRINI LOUD"],
      ["D"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["D"],
      ["MD RIVRI"],
      ["MD RIVRI"],
      ["MD RIVRI"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["MD SAMONI", "IVOS"],
      ["MD SAMONI", "IVOS"],
      ["D AMB", "IVOS"],
      ["D", "IVOS"],
      ["D AMB", "IVOS"],
      ["IIT D"],
      ["IIT D RIVRI AMB"],
      ["D PETIUX RIV ANAG"],
      ["D AMB RIVRI"],
      ["D"],
      ["D AMB", "[IVOS]"],
      ["N INIS R", "[IVOS]"],
      ["D AMB", "IVOS"],
      ["D", "IVOS"],
    ],
    [
      ["SAM PRINI LOUD EXO", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAGET"],
      ["ITI D"],
      ["N INIS R"],
      ["N SAMONI"],
      ["D"],
      ["D"],
      ["N INIS R"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["D"],
      ["MD SAMONI"],
      ["MD SAMONI"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["IIT M D"],
      ["D AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["NSDS"],
    ],
  ],
  "Riuros": [
    [
      ["D ANAGANT EXO", "IVOS"],
      ["PRINI LOUD", "IVOS"],
      ["MD", "IVOS"],
      ["(MD) BRIGIOMU RIVRI"],
      ["N INIS R"],
      ["MD"],
      ["ITI D ANAGANT"],
      ["IIT D ANAGANT"],
      ["D ANAGANT"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["DEC/VOR LUG RIVRI"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["N ANAG INIS R"],
      ["D ANAG"],
      ["N ANAG INIS R"],
      ["MD PETIUX RIVRI"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
    ],
    [
      ["D ANAGANT"],
      ["PRINI LOUD"],
      ["N"],
      ["(MD) BRIGIOMU RIVRI"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["ITI MD"],
      ["IIT MD"],
      ["N INIS R"],
      ["MD"],
      ["DEC/VOR LUG RIV"],
      ["NSDS", "IVOS"],
      ["DSNS", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["TII D AMB", "IVOS"],
      ["ITT MD"],
      ["IIT D AMB"],
      ["D PETIUX ANAG"],
      ["D AMB"],
      ["IIT MD PETIUX RIVRI"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["D ANAGANT"],
      ["PRINI LOUD"],
      ["N"],
      ["(MD) BRIGIOMU RIVRI"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["ITI MD"],
      ["IIT MD"],
      ["N INIS R"],
      ["MD"],
      ["DEC/VOR LUG RIV"],
      ["NSDS", "IVOS"],
      ["N", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["TII D AMB", "IVOS"],
      ["ITT MD"],
      ["IIT D AMB"],
      ["D PETIUX ANAG"],
      ["N"],
      ["IIT MD PETIUX RIVRI"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["D ANAGANT EXO", "IVOS"],
      ["PRINI LOUD", "IVOS"],
      ["MD", "IVOS"],
      ["(MD) BRIGIOMU RIVRI"],
      ["N INIS R"],
      ["MD"],
      ["D ANAGANTIOS"],
      ["D ANAGANT"],
      ["D ANAGANT"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["DEC/VOR LUG RIVRI"],
      ["NSDS MAT"],
      ["DS MAT NS"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB"],
      ["ITT MD"],
      ["N ANAG INIS R"],
      ["D ANAG"],
      ["N ANAG INIS R"],
      ["MD PETIUX RIVRI"],
      ["TII D AMB"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["MD"],
      ["D"],
    ],
    [
      ["D ANAGANT"],
      ["PRINI LOUD"],
      ["MD"],
      ["(MD) BRIGIOMU RIVRI"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["N"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["DEC/VOR LUG RIV"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["[TII] D AMB", "IVOS"],
      ["[ITT] IIT MD"],
      ["[IIT] D AMB"],
      ["D PETIUX ANAG"],
      ["D AMB"],
      ["MD PETIUX RIVRI"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
  ],
  "Anagantios": [
    [
      ["MD RIVRI"],
      ["D"],
      ["D"],
      ["MD OGIOUMU RIVRI"],
      ["N INIS R"],
      ["PRINI LAG"],
      ["MD OGRONI"],
      ["MD OGRONI"],
      ["MD OGRONI"],
      ["D"],
      ["D AMB"],
      ["TII D"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["D"],
      ["D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["N INIS R"],
      ["D AMB OGRON"],
      ["MD CVTI OGRON"],
      ["D OGRON AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD RIVRI IX", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["N OGIOUMU RIVRI"],
      ["N INIS R"],
      ["PRINI LAG"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["D"],
      ["N INIS R"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD RIVRI IX", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["N OGIOUMU RIVRI"],
      ["N INIS R"],
      ["PRINI LAG"],
      ["NSDS"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["N"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD RIVRI"],
      ["D"],
      ["D"],
      ["MD OGIOUMU RIVRI"],
      ["N INIS R"],
      ["PRINI LAG (ANAG)"],
      ["MD OGRONI"],
      ["MD OGRONI"],
      ["MD OGRONI"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["N INIS R"],
      ["ITI D AMB OGRON"],
      ["ITI MD CVTI OGRON"],
      ["D OGRON AMB"],
      ["NSDS"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD RIVRI IX", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["MD OGIOUMU RVRI"],
      ["N INIS R"],
      ["PRINI LAG"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["N"],
      ["D AMB"],
      ["TII D"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["D"],
      ["D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["N INIS R"],
      ["N INIS R"],
      ["D"],
      ["N INIS R"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
  ],
  "Ogronios": [
    [
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["MD CVTI"],
      ["MD CVTI"],
      ["N CVTI INIS R"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD CVTI"],
      ["MD CVTI"],
      ["D CVTI AMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["D AMB QVTI"],
      ["MD OGRON QVTI"],
      ["D AMB QVTI"],
      ["MD"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["ITI MD"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["N"],
      ["TII MD CVTI"],
      ["ITI MD CVTI"],
      ["IIT D CVTI AMB"],
      ["MD"],
      ["D AMB"],
      ["TIT MD"],
      ["ITI D AMB"],
      ["ITI MD QVTI"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["N INIS R"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
    ],
    [
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["ITI MD"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["N"],
      ["TII MD CVTI"],
      ["N CVTI"],
      ["IIT D CVTI AMB"],
      ["MD"],
      ["D AMB"],
      ["TIT MD"],
      ["ITI D AMB"],
      ["ITI MD QVTI"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["N INIS R"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
    ],
    [
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["MD CVTIO"],
      ["MD CVTIO"],
      ["N CVTIO INIS R"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["N"],
      ["TII MD CVTI"],
      ["ITI MD CVTI"],
      ["TII D CVTI AMB"],
      ["MD"],
      ["D AMB"],
      ["TIT MD"],
      ["TII D AMB QVTI"],
      ["ITI MD OGRON QVTI"],
      ["IIT D AMB QVTI"],
      ["MD"],
      ["D AMB"],
      ["N INIS R"],
      ["ITI D AMB", "IVOS"],
      ["IIT MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["N"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD CVTIO"],
      ["MD CVTIO"],
      ["D CVTIO AMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD QVTIO"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["N INIS R"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
    ],
  ],
  "Cutios": [
    [
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["PRINI LOUD"],
      ["N INIS R"],
      ["MD"],
      ["GIAM PRINI LAG"],
      ["D GIAM"],
      ["N GIAM INIS R"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD OGRON"],
      ["MD OGRON"],
      ["D OGRON AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["N INIS R"],
      ["N GIAM INIS R"],
      ["N GIAM INIS R"],
      ["D AMB GIAM"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
    ],
    [
      ["MD"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["N INIS R"],
      ["N"],
      ["MD"],
      ["MD"],
      ["N INIS R"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD OGRON"],
      ["MD OGRON"],
      ["D OGRON AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["N INIS R"],
      ["TII D AMB"],
      ["IIT MD OGRONI"],
      ["IIT D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
    ],
    [
      ["MD"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["N INIS R"],
      ["N"],
      ["MD"],
      ["MD"],
      ["N INIS R"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD OGRON"],
      ["MD OGRON"],
      ["N OGRON"],
      ["N INIS R"],
      ["D AMB"],
      ["N INIS R"],
      ["TII D AMB"],
      ["IIT MD OGRONI"],
      ["IIT D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
    ],
    [
      ["MD"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["N INIS R"],
      ["MD"],
      ["MD CVTIO"],
      ["MD CVTIO"],
      ["N CVTIO INIS R"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD OGRON"],
      ["MD OGRON"],
      ["D OGRON AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["N INIS R"],
      ["TII D AMB QVTI"],
      ["ITI MD OGRON QVTIO"],
      ["TII D AMB QVTI"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB", "IVOS"],
      ["ITI MD", "IVOS"],
      ["IIT D AMB", "IVOS"],
    ],
    [
      ["MD"],
      ["MD"],
      ["MD"],
      ["PRINI LOUD"],
      ["N INIS R"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["N INIS R"],
      ["MD"],
      ["D AMB"],
      ["N"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD OGRON"],
      ["MD OGRON"],
      ["D OGRON AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["MD OGRONI"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
  ],
  "Rantaranos": [
    [],
    [],
    [
      ["D SAMON DUMAN", "IVOS"],
      ["D DUMANI", "IVOS"],
      ["(ITI) MD RIVRI", "IVOS"],
      ["MD OCIOMV RIVRI AN", "--]T ANAG"],
      ["N OGRON", "INNIS R"],
      ["(IIT) MD CUTI"],
      ["GIAMON PRINI LAG", "[---", "[---"],
      ["D GIAM SIMVIS"],
      ["N GIAMO EQVI", "INNIS R"],
      ["N ELEMB INIS R"],
      ["D EDRINI AMB"],
      ["IIT D CANTLI"],
      ["TII MD SAMONI"],
      ["D DUMANNI"],
      ["DS MD NS RIVR"],
      ["D ANAGAN"],
      ["ITI MD QVTI OGRON"],
      ["D OGRONI QVT (AMB)"],
      ["D GIAMONI"],
      ["D SIMIS AMB"],
      ["IIT D SIMIS EQUI"],
      ["N GIAMONI", "ELEMBI"],
      ["N GIAMONI", "AEDRINNI"],
      ["D GIAMO CANT", "AMB RIXR"],
      ["TII MD SAMON"],
      ["D DUMAN AMB"],
      ["ITI MD RIVRI"],
      ["D ANAG AMB"],
      ["IIT D M OGRONV"],
      ["IIT D AMB QVT"],
    ],
    [],
    [],
  ],
  "Giamonios": [
    [
      ["MD SIMIUISONNA"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["MD SIMIU TIOCOBREXTIO"],
      ["MD SIMIUISONNA"],
      ["MD SIMIU SINDIU IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["NSDS"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D SIMIUI AMB"],
      ["MD SIMIUISONNA"],
      ["D SIMIUIS AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD SIMUISONNA EXO", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["N PRINI LAG"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["NSDS"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["N INIS R"],
      ["N INIS R"],
      ["D AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["MD SIMUISONNA"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["IIT MD SIMIU TIOCOBREXTIO"],
      ["MD SIMIUSONNA"],
      ["MD SIMIU SINDIU", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["NSDS"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["IIT D"],
      ["D SIMIUI AMB"],
      ["TII MD SIMIUISONNA"],
      ["ITI D SIMIUIS AMB"],
      ["D"],
      ["N INIS R"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["N SIMIUISONNA EXO", "IVOS"],
      ["ITI D", "IVOS"],
      ["IIT D", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D"],
      ["N INIS R"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["NSDS"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["N INIS R"],
      ["N INIS R"],
      ["D AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["N SIMIUISONNA EXO", "IVOS"],
      ["ITI D", "IVOS"],
      ["IIT D", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D"],
      ["N INIS R"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["N"],
      ["ITI D"],
      ["IIT D"],
      ["D"],
      ["NSDS"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["N INIS R"],
      ["N INIS R"],
      ["D AMB"],
      ["TII D"],
      ["N INIS R"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
    ],
  ],
  "Simiuisonna": [
    [
      ["GIAM PRINI LAG"],
      ["MD"],
      ["D EQVI"],
      ["MD"],
      ["N INIS R"],
      ["D EQVI"],
      ["D EQVI"],
      ["PRINI LAG EQVI"],
      ["D EQVI"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D EQVI"],
      ["NSDS EQVI"],
      ["DSNS EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D EQVI AMB"],
      ["MD"],
      ["D AMB"],
      ["ITT D EQVI"],
      ["IIT D EQVI AMB"],
      ["D EQVI"],
      ["D AMB EQVI"],
      ["MD"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["GIAM PRINI LAG"],
      ["MD"],
      ["D EQVI"],
      ["MD"],
      ["N INIS R"],
      ["D EQVI"],
      ["IIT MD TIOCOBREXTIO"],
      ["N"],
      ["MD SINDIU", "IVOS"],
      ["MD"],
      ["TII D AMB"],
      ["ITI MD"],
      ["D EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D AMB EQVI"],
      ["IIT MD"],
      ["D AMB"],
      ["IIT D EQVI"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["NSDS (AMB)"],
      ["DSNS AMB"],
    ],
    [
      ["GIAM PRINI LAG"],
      ["MD"],
      ["D EQVI"],
      ["MD"],
      ["N INIS R"],
      ["D EQVI"],
      ["D EQVI"],
      ["PRINI LAG EQVI"],
      ["D EQVI"],
      ["MD"],
      ["TII D AMB"],
      ["ITI MD"],
      ["D EQVI"],
      ["NSDS EQVI"],
      ["DSND EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D EQVI AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["ITT D EQVI"],
      ["D EQVI AMB"],
      ["D EQVI"],
      ["D AMB EQVI"],
      ["IIT MD"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
      ["NSDS", "IVOS"],
      ["DSNS", "IVOS"],
    ],
    [
      ["GIAM PRINI LAG"],
      ["N"],
      ["ITI D EQVI"],
      ["MD"],
      ["N INIS R"],
      ["D EQVI"],
      ["MD TIOCOBREXTIO"],
      ["MD"],
      ["MD SINIDIU", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D EQVI"],
      ["NSDS EQVI"],
      ["DSNS EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D AMB EQVI"],
      ["IIT MD"],
      ["D AMB"],
      ["ITT D EQVI"],
      ["D AMB"],
      ["TII MD"],
      ["ITI D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["NSDS"],
      ["DSNS"],
    ],
    [
      ["GIAM PRINI LAG"],
      ["N"],
      ["ITI D EQVI"],
      ["MD"],
      ["N INIS R"],
      ["D EQVI"],
      ["MD TIOCOBREXTIO"],
      ["MD"],
      ["MD SINDIU", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D EQVI"],
      ["N EQVI"],
      ["DSNS EQVI"],
      ["D EQVI"],
      ["D EQVI"],
      ["D AMB EQVI"],
      ["MD"],
      ["D AMB"],
      ["ITT D EQVI"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
    ],
  ],
  "Equos": [
    [
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["MD SIMIVIS", "IVOS"],
      ["D", "IVOS"],
      ["D AMB"],
      ["MD SIMIVISO"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["MD SIMI"],
      ["MD SIMI"],
      ["MD SIMI ganor"],
      ["MD SIMIVIS"],
      ["MD SIMIVIS"],
      ["D AMB SIMIVIS"],
      ["D"],
      ["TII D AMB"],
      ["IIT (M)D SIMIVIS"],
      ["ITI D ELEMB AMB"],
      ["IIT D ELEMB"],
      ["D AMB ELEMB"],
      ["D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
    ],
    [
      ["D"],
      ["PRINI LAG"],
      ["MD SINIVIS"],
      ["D"],
      ["D AMB"],
      ["ITI MD SIMIVISO"],
      ["D"],
      ["PRINI LAG"],
      ["N"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["IIT MD SIMI"],
      ["MD SIMI"],
      ["MD SIMI"],
      ["MD SIMIVIS"],
      ["TII MD SIMIVIS"],
      ["ITI D AMB SIMIVIS"],
      ["D"],
      ["TII D AMB"],
      ["IIT (M)D SIMIVIS"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["ITI D", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["D", "IVOS"],
    ],
    [
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["MD SIMIVIS", "IVOS"],
      ["D", "IVOS"],
      ["D AMB"],
      ["ITI MD SIMIVISO"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["IIT MD SIMI"],
      ["MD SIMI"],
      ["MD SIMI"],
      ["MD SIMIVIS"],
      ["TII MD SIMIVIS"],
      ["ITI D AMB SIMIVIS"],
      ["D"],
      ["TII D AMB"],
      ["IIT MD SIMIVIS"],
      ["D ELEMB AMB"],
      ["D ELEMB"],
      ["D AMB ELEMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["D"],
      ["PRINI LAG"],
      ["N SIMIVIS"],
      ["IIT D"],
      ["D AMB"],
      ["MD SIMIVISO"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["MD SIMI"],
      ["MD SIMI"],
      ["MD SIMI"],
      ["MD SIMIVIS"],
      ["TII MD SIMIVIS"],
      ["ITI D AMB SIMIVIS"],
      ["D"],
      ["TII D AMB"],
      ["IIT MD SIMIVIS"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["ITI D", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["D", "IVOS"],
    ],
    [
      ["D"],
      ["PRINI LAG"],
      ["N SIMIVIS"],
      ["IIT D"],
      ["D AMB"],
      ["MD SIMIVISO"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["MD SIMIV"],
      ["MD SIMIV"],
      ["N SIMIV"],
      ["MD SIMIVIS"],
      ["MD SIMIVIS"],
      ["D AMB SIMIVIS"],
      ["D"],
      ["TII D AMB"],
      ["IIT MD SIMIVIS"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["ITI D", "IVOS"],
      ["IIT D AMB", "IVOS"],
      ["D", "IVOS"],
      ["D AMB", "IVOS"],
    ],
  ],
  "Elembi": [
    [
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["MD EDRINNI [TIOGBR?]"],
      ["MD EDRI TIOCOBREXTIO"],
      ["MD EDRINNI"],
      ["N INIS R"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["N"],
      ["MD EDRIN"],
      ["MD EDRIN"],
      ["D EDRIN AMB"],
      ["D"],
      ["D AMB"],
      ["TIT D"],
      ["D EDRIN AMB"],
      ["MD EDRINI"],
      ["D AMB EDRINI"],
      ["D SINDIV IVOS"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
    ],
    [
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["D", "IVOS"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["N INIS R"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["(N)"],
      ["MD EDRIN"],
      ["MD EDRIN"],
      ["TII D EDRIN AMB"],
      ["D"],
      ["D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
    ],
    [
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["ITI MD EDRINNI TIOGBR?"],
      ["IIT MD EDRI TIOCOBREXTIO"],
      ["MD EDRINNI"],
      ["N INIS R"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["MD EDRIN"],
      ["MD EDRIN"],
      ["TII D EDRIN AMB"],
      ["D"],
      ["D AMB"],
      ["IIT D"],
      ["D EDRIN AMB"],
      ["MD EDRINI"],
      ["TII D AMB EDRINI"],
      ["D SINDIU IVOS"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
    ],
    [
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["N", "IVOS"],
      ["IIT D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["N INIS R"],
      ["IIT D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["N"],
      ["MD EDRIN"],
      ["MD EDRIN"],
      ["TII D EDRIN AMB"],
      ["D"],
      ["D AMB"],
      ["TIT D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
    ],
    [
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG", "IVOS"],
      ["N", "IVOS"],
      ["IIT D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["N INIS R"],
      ["IIT D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["N"],
      ["N EDRIN"],
      ["MD EDRIN"],
      ["D EDRIN AMB"],
      ["D"],
      ["D AMB"],
      ["TIT D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
    ],
  ],
  "Aedrinni": [
    [
      ["D CANTLI"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["PRINI LOUD"],
      ["D CANTLI"],
      ["D CANTLI"],
      ["D CANTLI"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D AMB ELEMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["TII D CANTL AMB"],
      ["ITI D CANTL"],
      ["IIT D CANTL AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["D AMB", "IVOS"],
    ],
    [
      ["D CANTLI", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD"],
      ["D AMB"],
      ["PRINI LOUD"],
      ["ITI MD TIOGBR?"],
      ["IIT MD TIOCOBREXTIO"],
      ["MD"],
      ["MD"],
      ["N"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT MD"],
      ["MD"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D ELEMB AMB"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB"],
      ["ITI D SINDIV", "IVOS"],
      ["IIT D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["N"],
    ],
    [
      ["D CANTLI"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["PRINI LOUD"],
      ["D CANTI"],
      ["D CANTI"],
      ["D CANTI"],
      ["MD"],
      ["D AMB"],
      ["TII MD"],
      ["ITI MD"],
      ["IIT MD"],
      ["MD"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D AMB ELEMB"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["IIT MD"],
      ["D CANTLAMB"],
      ["D CANTL"],
      ["D CANTLAMB"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["MD"],
      ["D AMB", "IVOS"],
      ["MD", "IVOS"],
      ["N", "IVOS"],
    ],
    [
      ["D CANTLI", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD"],
      ["N"],
      ["PRINI LOUD"],
      ["MD [TIOGBR?]"],
      ["MD TIOCOBREXTIO"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D ELEMB"],
      ["D ELEMB"],
      ["D ELEMB AMB"],
      ["ITI MD"],
      ["IIT D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["TII D AMB"],
      ["ITI D SINDIV", "IVOS"],
      ["IIT D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["N"],
    ],
    [
      ["D CANTLI", "IVOS"],
      ["MD", "IVOS"],
      ["MD", "IVOS"],
      ["MD"],
      ["N"],
      ["PRINI LOUD"],
      ["MD [TIOGBR?]"],
      ["MD TIOCOBREXTIO"],
      ["MD"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["MD"],
      ["D ELEMB"],
      ["N ELEMB"],
      ["D ELEMB AMB"],
      ["MD"],
      ["D AMB"],
      ["IIT MD"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD SINDIV IVOS"],
      ["D AMB"],
      ["MD"],
      ["D AMB"],
      ["MD"],
      ["N"],
    ],
  ],
  "Cantlos": [
    [
      ["MD AEDRIN"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["D AMB"],
      ["D"],
      ["D CANTLI"],
      ["D CANTLI"],
      ["D CANTLI"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D TIOCOBREXTIO"],
      ["TII D"],
      ["ITI D"],
      ["IIT D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["IIT D"],
      ["TII D CANTL AMB"],
      ["ITI D CANTL"],
      ["IIT D CANTL AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII (IIT) D AMB IVO"],
      ["ITI D IVO DIB CANTL"],
    ],
    [
      ["MD AEDRIN"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["N"],
      ["D"],
      ["D"],
      ["D TIOCOBREXTIO"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["IIT D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["ITI D", "IVOS"],
    ],
    [
      ["MD AEDRIN", "IVOS"],
      ["D", "IVOS"],
      ["D", "IVOS"],
      ["PRINI LAG"],
      ["D AMB"],
      ["D"],
      ["SAMON PRINI LOUD"],
      ["D DUMANNI (SAMONI)"],
      ["MD SAMONI"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["D"],
      ["D"],
      ["D TIOCOBREXTIO"],
      ["D"],
      ["D"],
      ["D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["IIT D"],
      ["D AMB SAMONI"],
      ["N SAMONI INIS R"],
      ["N SAMONI INIS R"],
      ["D"],
      ["D AMB", "IVOS"],
      ["D", "IVOS"],
      ["D AMB", "IVOS"],
      ["D", "IVOS"],
    ],
    [
      ["MD AEDRIN"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D AMB"],
      ["N"],
      ["D"],
      ["D"],
      ["D"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D"],
      ["D"],
      ["D TIOCOBREXTIO"],
      ["TII D"],
      ["ITI D"],
      ["IIT D AMB"],
      ["N INIS R"],
      ["D AMB"],
      ["IIT D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["ITI D", "IVOS"],
    ],
    [
      ["MD AEDRIN"],
      ["D"],
      ["D"],
      ["PRINI LAG"],
      ["ITI D AMB"],
      ["N"],
      ["D"],
      ["D"],
      ["D"],
      ["TII D"],
      ["ITI D AMB"],
      ["IIT D"],
      ["D"],
      ["D"],
      ["D TIOCOBREXTIO"],
      ["TII D"],
      ["ITI D"],
      ["N"],
      ["N INIS R"],
      ["D AMB"],
      ["IIT D"],
      ["TII D AMB"],
      ["ITI D"],
      ["IIT D AMB"],
      ["D"],
      ["D AMB"],
      ["D"],
      ["TII D AMB", "IVOS"],
      ["(ITI) D", "IVOS"],
    ],
  ],
};
